<a href="https://colab.research.google.com/github/bmcristin/Ingeniasrepo/blob/main/Notebook_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [ ]:
import numpy as np

In [ ]:
array1 = np.zeros(12)

print(array1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
array2 = np.zeros(10)
array2[5] = 10
print(array2)

[ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]


In [ ]:
array3 = np.arange(10,49,1)
print(array3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
array4 = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(array4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
array5 = np.random.randint(0,100,100)
#print(array5)
print(f"La media es {np.mean(array5)}")
print(f"La varianza es {np.var(array5)}")
#ejercicio 6
mediamanual = np.sum(array5)/array5.size
print(f"La media manual es de {mediamanual}")
#ejercicio 7
varianza = np.sum((array5 - mediamanual)**2) / len(array5)
print(f"La varianza manual es de {varianza}")


La media es 49.93
La varianza es 788.3250999999999
La media manual es de 49.93
La varianza manual es de 788.3250999999999


In [ ]:
array8 = np.random.randn(12)
print(array8)

[-0.12079134 -0.72386087 -0.06921607 -1.20417777 -0.59218446 -0.73804654
 -1.15535951 -1.57308992  1.31099109  0.84389019 -0.86426305 -0.3909547 ]
